### ISSUE TITLE
[建议]能否新增一个随机时间运行的功能

### ISSUE THREAD

**Issue by Qliangw** [SuperNG6/docker-bilibili-helper#34]
如题
-----------
看到有反馈说是遇到封号的问题,具体没有详细看
我写了一个生成随机时间的定时任务脚本,经测试可正常使用.效果如下
![](https://raw.githubusercontent.com/Qliangw/Miscellaneous/main/scripts/randomTimeCrontab_%E6%95%88%E6%9E%9C%E5%9B%BE.png)

能否在后续版本中增加该功能
------------
脚本详情[https://raw.githubusercontent.com/Qliangw/Miscellaneous/main/scripts/randomTimeCrontab.sh](url)

**Comment by SuperNG6** [comment]
下个版本会实现在一天内的某个随机时间点执行任务，不过我觉得封号的原因应该不是这个

**Comment by SuperNG6** [comment]
已支持

**Comment by Qliangw** [comment]
> 已支持
> `-e CRON=random`

当前产生随机时间的脚本有些小问题:

1. 现在的随机产生如果在当前运行时间之后,今天还会再次重复运行bh-run.sh脚本
2. 如果产生的随机时间为23:59,那今天就会出现断签的问题

那么需要将运行产生随机时间的脚本固定下来,
而不是在运行bh-run.sh时就运行.

---------

- 修改random-bh.sh脚本中部分:

      if [ "${CRON}" = random ]
      then
      cat > /config/bh-crontab << EOF 
      ....
        0                               1                             *       *       *      /app-conf/random-bh.sh
        $[RANDMINUTE]     $[RANDHOUR]       *       *       *      /app-conf/bh-run.sh
      EOF
      else
      现有的
      fi

--------------

仅是大概逻辑,大佬有时间看看修复一下当前一天运行多次的情况

**Comment by SuperNG6** [comment]
这样应该是不行的，通过cron运行bh，只要修改cron配置，就要重载cron，不能够保证生成的时间不在今天运行之后，得从其他地方着手，这两天应该会修复这个问题
在 2021年9月26日 +0800 AM9:35，Jason_Smith ***@***.***>，写道：

**Comment by SuperNG6** [comment]
已修复
