### ISSUE TITLE
创建docker报错

### ISSUE THREAD

**Issue by 1525249038** [SuperNG6/docker-bilibili-helper#9]
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by SuperNG6** [comment]
是不是选错平台了


Architecture | Tag
-- | --
x86-64 | latest
arm64 | arm64-latest
arm32 | arm32-latest

**Comment by 1525249038** [comment]
![image](https://user-images.githubusercontent.com/46812909/100963911-6e634a00-3562-11eb-8c14-24c212a05cf8.png)

**Comment by SuperNG6** [comment]
`superng6/bilibili-helper:arm64-latest`

**Comment by 1525249038** [comment]
> `superng6/bilibili-helper:arm64-latest`


![image](https://user-images.githubusercontent.com/46812909/100971431-da00e380-3571-11eb-8549-3301150b077b.png)

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; docker pull 'superng6/bilibili-helper:arm64-latest:bilibili'' with exit code '1':

**Comment by SuperNG6** [comment]
你输入错了，看错误提示
参数输入`superng6/bilibili-helper`，标签输入`arm64-latest`

**Comment by 1525249038** [comment]
> 你输入错了，看错误提示
> 源输入`superng6/bilibili-helper`，标签输入`arm64-latest`

好了，多谢大大在百忙之中管我这个小白！！！！
